[package]
name = "skani-lib-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skani = "0.1.0"

[profile.dev]
opt-level = 3
